### ISSUE TITLE
Not all buildings are counted

### ISSUE THREAD

**Issue by maning** [developmentseed/osm-coverage-tiles#1]
Thanks for this tool! I'm testing the tool in the Philippines and I found 2 issues related to building data.

Steps to re-produce.

1. Download osm-qa-tiles for the Philippines at: https://osmlab.github.io/osm-qa-tiles/country.html
2. Run `osmcov philippines.mbtiles --zoom=12 > osm-coverage.json`
3. Convert ldjson to geojson `ogr2ogr -of GeoJSON osm-coverage.geojson osm-coverage.json`
4. Visualize in QGIS.

Issues I found are the following:

**1. Areas that have buildings don't have tiles.**  See for example, east section of this island:
<img width="676" alt="Screenshot 2019-04-24 16 15 07" src="https://user-images.githubusercontent.com/353700/56644062-88158d80-66ad-11e9-9728-892847bae4d6.png">

For reference, here's the geojson of the tile adjacent to the [missing section](https://gist.github.com/maning/6cf10dbafb58ac2c4616b687a649847a) .  The only thing I observed which may be causing this is that there are buildings in the msising tile bu there are no roads.

**2. Buildings in certain tiles are not computed for area.**  See example below, the center tile higleghted don't have an `area` value.  Reference tile in [geojson here](https://gist.github.com/maning/ec914457392c327453616d9a421b3088).

<img width="902" alt="Screenshot 2019-04-24 16 27 25" src="https://user-images.githubusercontent.com/353700/56644232-e2165300-66ad-11e9-966d-597d8f7ceb39.png">

**Comment by maning** [comment]
cc @Rub21

**Comment by Rub21** [comment]
Fix this issue in the new changes!! :)
cc. @maning!!

**Comment by Rub21** [comment]
also, you can add the type of object to filter per tile passing the argument `--types=building,highway,leisure`
